export const internshipProjects = [
  {
    slug: "liveops-configuration-automation",
    title: "LiveOps Configuration Automation",
    status: "Completed · In use",
    summary: "AI-powered automation for recurring LiveOps configuration packs.",
    metric: "Reduced configuration creation from ~5 days to ~1 hour.",
    description: "An automation pipeline that generates, validates, and formats Google Sheets configuration packs for Tentpole events, offers, Battle Passes, and event design from structured inputs.",
    highlights: ["Uses n8n workflows, Google Sheets, Google Apps Script, and an AI analysis layer.", "Produces consistent, repeatable, sheet-ready configuration data.", "Generates Admin Tool import assets after validation and formatting checks."],
  },
  {
    slug: "lova-liveops-validation-agent",
    title: "LOVA — LiveOps Validation Agent",
    status: "Completed · In use",
    summary: "AI-assisted validation of LiveOps specifications and configuration snapshots.",
    metric: "Reduced validation from ~4 working days per cycle to ~2 hours per month.",
    description: "LOVA translates specifications into structured requirements, compares them against configuration snapshots, and delivers a traceable validation report to QA and LiveOps.",
    highlights: ["Combines deterministic checks with LLM-assisted business and semantic validation.", "Reports passes, failures, warnings, expected values, actual values, and mismatch details.", "Built with LangChain, LangGraph, LiteLLM, MariaDB, FastAPI, AWS EC2, Jenkins, and Slack."],
  },
  {
    slug: "casino-log-analyser",
    title: "Casino Log Analyser — Live Issues Resolver",
    status: "Completed · Final testing",
    summary: "AI-powered initial diagnosis for live Customer Support issues.",
    metric: "Creates a single evidence-based path from a CS ticket to likely root cause.",
    description: "The resolver ingests CS tickets, logs, analytics, gameplay traces, code context, Jira issues, and commit history to identify likely causes and recommended next steps.",
    highlights: ["Builds an investigation timeline across gameplay, transactions, rewards, and backend events.", "Detects gaps such as unmatched bets, duplicate transactions, and unexpected balance changes.", "Can surface historical context and propose bug-fix pull requests for suitable issues."],
  },
  {
    slug: "onboarding-platform",
    title: "Adaptive Employee Learning & Readiness Platform",
    status: "In development",
    summary: "A personalized AI onboarding companion for new team members.",
    metric: "Designed to shorten ramp-up time and reduce repetitive mentor support.",
    description: "The platform adapts onboarding plans by role and progress, answers questions from organizational knowledge, verifies understanding, and tracks readiness for managers.",
    highlights: ["Personalized learning plans and contextual knowledge assistance.", "Competency verification through quizzes, scenarios, and practical tasks.", "Readiness scoring and manager visibility into progress, gaps, and blockers."],
  },
  {
    slug: "character-kit-generator",
    title: "Character Kit Generator — Toon Skill Implementation",
    status: "In progress",
    summary: "An AI co-designer for game character skill kits and balance exploration.",
    metric: "Aims to cut toon skill brainstorming and drafting time by at least 50%.",
    description: "The tool reasons over historical toon data, game meta patterns, combat logs, and designer documentation to help combat designers create coherent, balanced skill-kit drafts.",
    highlights: ["Generates kit concepts, variants, counters, and team-composition suggestions.", "Supports prompt- or UI-driven design iteration.", "Targets documentation-ready output aligned with game tone and balance rules."],
  },
  {
    slug: "automatic-looker-dashboard-creation",
    title: "Automatic Looker Dashboard Creation",
    status: "Paused · 30% complete",
    summary: "Exploration of automated Looker dashboard setup.",
    metric: "Intended to make dashboard creation faster, more consistent, and scalable.",
    description: "This project explored automating repetitive Looker dashboard setup, including view definitions, chart arrangement, and report configuration from business requirements.",
    highlights: ["Focuses on reducing manual dashboard configuration.", "Targets consistency across multiple reporting needs.", "Currently paused after initial development."],
  },
  {
    slug: "ai-player-coach",
    title: "AI Player Coach — Black Market",
    status: "Ideation",
    summary: "Behaviour-driven guidance for early game users.",
    metric: "Designed to improve player understanding and discovery of relevant store items.",
    description: "The proposed AI coach would use player behaviour signals to offer timely, contextual guidance on game mechanics, next actions, rewards, and overlooked store items.",
    highlights: ["Uses signals such as onboarding progress, failed actions, feature inactivity, and session history.", "Explains why a recommended item or action matters in the player’s current journey.", "Remains in the ideation phase."],
  },
] as const;

export type InternshipProject = (typeof internshipProjects)[number];
